package lexer


type Tag int

const (
	AXIOM Tag = iota
	TERM
	NTERM
	RULE
	EPS
	EPSILON
	IDENT
	STRING
	EQUAL
	SPACES
	PLUS
	STAR
	QUESTION
	LEFT_SQUARE_PAREN
	RIGHT_SQUARE_PAREN
	LEFT_FIGURE_PAREN
	RIGHT_FIGURE_PAREN
	COLON
	COMMA
	END_OF_PROGRAM
	ERROR
	NOT_FINAL
	NEW_LINE
	FINAL
)

var TagToString = map[Tag]string {
	AXIOM: "AXIOM",
	TERM: "TERM",
	NTERM: "NTERM",
	RULE: "RULE",
	EPS: "EPS",
	EPSILON: "EPSILON",
	IDENT: "IDENT",
	STRING: "STRING",
	EQUAL: "EQUAL",
	SPACES: "SPACES",
	PLUS: "PLUS",
	STAR: "STAR",
	QUESTION: "QUESTION",
	LEFT_SQUARE_PAREN: "LEFT_SQUARE_PAREN",
	RIGHT_SQUARE_PAREN: "RIGHT_SQUARE_PAREN",
	LEFT_FIGURE_PAREN: "LEFT_FIGURE_PAREN",
	RIGHT_FIGURE_PAREN: "RIGHT_FIGURE_PAREN",
	COLON: "COLON",
	COMMA: "COMMA",
	END_OF_PROGRAM: "END_OF_PROGRAM",
	ERROR: "ERROR",
	NOT_FINAL: "NOT_FINAL",
	NEW_LINE: "NEW_LINE",
	FINAL: "FINAL",
}